# Generated by Django 5.0.5 on 2024-05-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RomanTemple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dedicatee', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('setting', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('modernplace', models.CharField(max_length=255)),
                ('ancientplace', models.CharField(max_length=255)),
                ('pleiadesplace', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('orientation', models.CharField(max_length=255)),
                ('compass', models.CharField(max_length=255)),
                ('geocertainty', models.IntegerField()),
                ('vowed', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('startdateearly', models.IntegerField()),
                ('startdatelate', models.IntegerField()),
                ('century', models.CharField(max_length=255)),
                ('enddate', models.CharField(max_length=255)),
                ('preceded', models.CharField(max_length=255)),
                ('succeeded', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('dedicationday', models.CharField(max_length=255)),
                ('deitytype', models.CharField(max_length=255)),
                ('culture', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('extant', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('meetings', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('vici', models.CharField(max_length=255)),
                ('pleiades', models.CharField(max_length=255)),
                ('dare', models.CharField(max_length=255)),
                ('arachne', models.CharField(max_length=255)),
                ('livius', models.CharField(max_length=255)),
                ('wikipedia', models.CharField(max_length=255)),
                ('wikidata', models.CharField(max_length=255)),
                ('digitalromanforum', models.CharField(max_length=255)),
                ('digitalesforumromanum', models.CharField(max_length=255)),
                ('trismegistos', models.CharField(max_length=255)),
                ('ads', models.CharField(max_length=255)),
                ('cona', models.CharField(max_length=255)),
                ('topostext', models.CharField(max_length=255)),
                ('sls', models.CharField(max_length=255)),
                ('patrimonium', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
